name: Check if Branch is allowed

runs:
  using: composite

  steps:
    - name: Print Env
      shell: sh
      run: printenv
      
    - name: Check Branch
      shell: sh
      run: |
        echo "Starting Deployment on ${{ github.ref }} Branch."
