name: Tag current Version
description: Tags the current version if it is an INT Deployment

inputs:
  env:
    description: Environment in which to deploy.
    type: string
  working-directory:
    description: git working dir
    type: string
    default: 'app'
  version:
    description: Version Number to tag the app repository with
    type: string
  
runs:
  using: composite

  steps:
    - name: Tagging
      if: ${{ inputs.env == 'int' && startsWith(github.ref, 'refs/maint') }}
      shell: bash
      # working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Tagging Version ${{ inputs.version }}"
        cd app
        git config --global user.email "michael@example.com"
        git config --global user.name "Michael"
        git tag -a ${{ inputs.version }}  -m "Version ${{ inputs.version }}"
        git push origin ${{ inputs.version }}

    - name: Nothing to do
      if: ${{ inputs.env != 'int' || ! startsWith(github.ref, 'refs/maint')}}
      shell: bash
      run: |
        echo "Nothing to do!"
        echo "Tagging only INT Deployments"
