name: Tag current Version
description: Tags the current version if it is an INT Deployment

inputs:
  env:
    description: Environment in which to deploy.
  working-directory:
    description: git working dir
  
runs:
  using: composite

  steps:
    - name: Tagging
      if: ${{ inputs.env == 'int' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Tagging Version ${{ github.ref_name }}"
        git config --global user.email "michael@example.com"
        git config --global user.name "Michael"
        git tag -a ${{ github.ref_name }}  -m "Version ${{ github.ref_name }}"
        git push origin ${{ github.ref_name }}

    - name: Nothing to do
      if: ${{ inputs.env != 'int' }}
      shell: bash
      run: |
        echo "Nothing to do!"
        echo "Tagging only INT Deployments"
