name: Checkout App and Modules Repository

runs:
  using: composite

  steps:
    - name: Output Secret
      shell: sh
      run: echo ${{ secrets.TEST_SECRET }}
      
    - name: Checkout App Repository
      uses: actions/checkout@v3
      with:
        path: 'app'

    - name: Checkout Modules Repository
      uses: actions/checkout@v3
      with:
        repository: mschmalzbauer/tf-modules
        path: 'tf-modules'
