name: Checkout App and Modules Repository
description: Checks if Deployment is allowed (Env & Branch/Tag) and checks out App and Modules Repo

inputs:
  env:
    description: Environment in which to deploy.
  github_ref:
    description: Branch or Tag from which to checkout
    
runs:
  using: composite

  steps:
    - name: Check Prerequisites
      if: ${{ inputs.env == 'dev' && ! startsWith(inputs.github_ref, 'refs/heads/maint') && ! startsWith(inputs.github_ref, 'refs/tags') ||
              inputs.env == 'int' && startsWith(inputs.github_ref, 'refs/heads/maint') ||
              inputs.env == 'prod' && startsWith(inputs.github_ref, 'refs/tags') }}
      id: check_prerequisites
      run: |
        echo "Started on ${{ inputs.github_ref }}"
        echo "deployment_allowed=true" >> $GITHUB_OUTPUT

    - name: Check Cancel Workflow
      if: ${{ steps.check_prerequisites.outputs.deployment_allowed != 'true' }}
      run: |
      echo "Deployment prerequisite not met!"
          echo "Environment: ${{ inputs.env }}"
          echo "Branch/Tag ${{ inputs.github_ref }}"
          exit 1
    
    - name: Checkout App Repository
      uses: actions/checkout@v4
      with:
        path: 'app'

    - name: Checkout Modules Repository
      uses: actions/checkout@v4
      with:
        repository: mschmalzbauer/tf-modules
        path: 'tf-modules'
    - name: List Content
      shell: sh
      run: ls -la
