name: Checkout App and Modules Repository

secrets:
  persToken:
  
runs:
  using: composite

  steps:
    - name: Checkout App Repository
      uses: actions/checkout@v3
      with:
        path: 'app'

    - name: Checkout Modules Repository
      uses: actions/checkout@v3
      with:
        repository: mschmalzbauer/tf-modules
        token: ${{ secrets.persToken }}
        path: 'tf-modules'
    - name: List Content
      shell: sh
      run: ls -la
