name: Execute Terraform
description: Executes Terraform 'Workflow' init, plan, apply

inputs:
  path:
    default: app
    
runs:
  using: composite

  steps:
    - name: Terraform setup
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init in App Directoy
      shell: sh
      run: |
        cd ${{ inputs.path }}
        terraform init

    - name: List App Directory
      shell: sh
      run: |
        cd ${{ inputs.path }}
        ls -la
