name: Execute Terraform
description: Executes Terraform 'Workflow' init, plan, apply

runs:
  using: composite

  steps:
    - name: Output Environment
      shell: bash
      run: printenv

    - name: Terraform setup
      uses: hashicorp/setup-terraform@v1
