name: Checkout

on:
  workflow_call:
    
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@2
        with:
          path: 'app'
          
      - name: checkout modules
        uses: actions/checkout@2
        with:
          repository: mschmalzbauer/tf-modules
          token: ${{ secrets.Token }}
          path: 'tf-modules'
